### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by samsonradu** [danavramescu/live-v2#3]
- Fix all buttons borders, now they don't match the button colors - keep in mind the various states :hover :active :focus (http://www.avajava.com/tutorials/lessons/how-do-i-use-the-hover-active-and-focus-pseudo-classes-to-format-links.html)

- ```B1``` ```B2``` ```B3``` have paddings messed up (or line-height) because the text is not vertically aligned

- glyphs instead of images for symbols

- apple.com navbar with the height, colors and font-size (it's awesome)

- div.sent-messages has extra side-paddings so it does not align with the chat form, needs to be removed

- <b>Model Name</b> bar should be opaque and over the webcam in a subtle way. I think LiveJasmin does that. We don t want a new block there.

- add another 2 colors to the page, say dark red and green (variables). use them for the cam2cam and credits button

**Comment by danavramescu** [comment]
fixed ,fixed ,fixed, it is awesome, fixed, fixed, done
